### PR TITLE
LINUXCN-21 Linux CN Panics when UEFI booting iPXE

### PR DESCRIPTION
**Pull request by danmcd**
- Merge with upstream ipxe (Oct 2023)
- remove .github/ for our downstream

### CODE REVIEW

**Comment by danmcd** [comment]
NOTE:  For pushing this I will be doing so by hand, to keep future upstream merges easy-ish.

**Comment by danmcd** [comment]
A question for the reviewers:

Should I keep the extra post-merge cleanup commit?  Or should I perform a re-merge that encapsulates the extra cleanup in the merge commit itself?

**Review by travispaul — DISMISSED** [review]

**Comment by danmcd** [comment]
A reminder that I'll be pushing this by hand.

**Comment by danmcd** [comment]
Closing PR as pushed (manually).

**Pull request closed without merging**
